package com.yicj.mvc.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.HashMap;
import java.util.Map;

@RestController
public class HelloController {

    @GetMapping("/hello")
    public Map<String,String> hello(){
        Map<String,String> map = new HashMap<>() ;
        map.put("code","200") ;
        map.put("msg","success") ;
        map.put("data", "successAAAAAAAABBBBBBBBBBBBBBBBBBBBCVCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDsuccessAAAAAAAABBBBBBBBBBBBBBBBBBBBCVCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDsuccessAAAAAAAABBBBBBBBBBBBBBBBBBBBCVCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDsuccessAAAAAAAABBBBBBBBBBBBBBBBBBBBCVCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDsuccessAAAAAAAABBBBBBBBBBBBBBBBBBBBCVCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDsuccessAAAAAAAABBBBBBBBBBBBBBBBBBBBCVCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDsuccessAAAAAAAABBBBBBBBBBBBBBBBBBBBCVCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDsuccessAAAAAAAABBBBBBBBBBBBBBBBBBBBCVCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDsuccessAAAAAAAABBBBBBBBBBBBBBBBBBBBCVCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDsuccessAAAAAAAABBBBBBBBBBBBBBBBBBBBCVCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDsuccessAAAAAAAABBBBBBBBBBBBBBBBBBBBCVCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDsuccessAAAAAAAABBBBBBBBBBBBBBBBBBBBCVCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDsuccessAAAAAAAABBBBBBBBBBBBBBBBBBBBCVCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDD") ;
        return map ;
    }
}
